output "bucket_name" {
  description = "R2 bucket created for this deployment."
  value       = module.artifact_pages.bucket_name
}

output "public_base_url" {
  description = "Public base URL for the deployment target configuration."
  value       = module.artifact_pages.public_base_url
}

output "artifact_pages_deployment_config_yaml" {
  description = "Non-secret Artifact Pages deployment configuration generated by the module."
  value       = module.artifact_pages.artifact_pages_deployment_config_yaml
}
