// Package registrysetup generates the operator-side files for the official
// site onboarding workflow. It is deliberately local-only: inputs are files,
// Action pins are embedded, and no GitHub client is used.
package registrysetup

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/artifact-pages/artifact-pages/cli/internal/config"
	"github.com/artifact-pages/artifact-pages/cli/internal/registry"
	"github.com/artifact-pages/artifact-pages/cli/internal/version"
	"go.yaml.in/yaml/v3"
)

//go:embed templates/*.tmpl
var templateFiles embed.FS

var (
	errDrift       = errors.New("generated files are out of date")
	regionPattern  = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)
	repositoryPart = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]*$`)
	roleARNPattern = regexp.MustCompile(`^arn:(aws|aws-us-gov|aws-cn):iam::([0-9]{12}):role/([A-Za-z0-9+=,.@_/-]+)$`)
	pinSHAPattern  = regexp.MustCompile(`^[0-9a-f]{40}$`)
)

const generatedHeader = "# Code generated by artifact-pages registry setup"

// Options are explicit so setup does not consult environment-based config
// locators, AWS credentials, or other machine state.
type Options struct {
	Directory       string
	ConfigPath      string
	TerraformOutput string
	Repository      string
	Check           bool
	Output          io.Writer
}

type templateData struct {
	CLI                  string
	Provider             string
	AWSRegion            string
	CloudflareEnv        []string
	PreviewCloudflareEnv []string
	PublishSHA           string
	PublishVersion       string
	PreviewSHA           string
	PreviewVersion       string
	RegistrySHA          string
	RegistryVersion      string
	AWSCredsSHA          string
	AWSCredsVersion      string
	RolesHash            string
}

type actionPin struct {
	SHA     string
	Version string
}

// These peeled tag commits were read from the official repositories when IMP-73
// was implemented. Keeping the values in source makes setup reproducible and
// usable without network access. Update this table only with a reviewed release.
var pins = map[string]actionPin{
	"artifact-pages/publish-action":         {SHA: "d59b7eceb7431c998bd2338eede1137081a141a2", Version: "v0.1.0"},
	"artifact-pages/preview-action":         {SHA: "9961a1de43f1ac7e6deb6598b9cfbed9fdab7acb", Version: "v0.1.0"},
	"artifact-pages/registry-action":        {SHA: "c5edcfaa4ae9a479cb52b3489daa8925cf5eec29", Version: "v0.1.0"},
	"aws-actions/configure-aws-credentials": {SHA: "e1253824e5c10ff9df46874f81ed3ec929e19cfd", Version: "v6.3.0"},
}

// Run validates local inputs and either writes the complete generated file set
// or reports drift without changing the filesystem.
func Run(options Options) error {
	if options.Output == nil {
		options.Output = io.Discard
	}
	if options.ConfigPath != "" && strings.Contains(options.ConfigPath, "://") {
		return errors.New("--config must be a local file path; remote config locators are not supported by registry setup")
	}
	root, err := resolveRoot(options.Directory)
	if err != nil {
		return err
	}
	configPath := options.ConfigPath
	if configPath == "" {
		configPath = "artifact-pages.yaml"
	}
	configBytes, err := readLocalInput(root, configPath, "deployment config")
	if err != nil {
		return err
	}
	deployment, err := config.Parse(configBytes)
	if err != nil {
		return fmt.Errorf("parse local deployment config: %w", err)
	}
	if deployment.Sites == nil {
		return errors.New("local deployment config must include a sites mapping (use sites: {} for an empty registry)")
	}
	if deployment.Provider != "cloudflare" && deployment.Provider != "aws" {
		return fmt.Errorf("registry setup supports cloudflare and aws providers; config uses %q", deployment.Provider)
	}

	data := templateData{CLI: version.Product, Provider: deployment.Provider}
	var rolesBytes []byte
	if deployment.Provider == "aws" {
		if deployment.AWS == nil || !regionPattern.MatchString(deployment.AWS.Region) {
			return errors.New("aws.region must contain lowercase letters, digits, or hyphens for the generated workflow")
		}
		if options.TerraformOutput == "" {
			return errors.New("--terraform-output is required for an AWS deployment; pass `terraform output -json satellite_role_arns` as a file")
		}
		terraformBytes, readErr := readLocalInput(root, options.TerraformOutput, "Terraform satellite_role_arns output")
		if readErr != nil {
			return readErr
		}
		roles, roleErr := parseRoles(terraformBytes, deployment)
		if roleErr != nil {
			return roleErr
		}
		rolesBytes, err = json.MarshalIndent(roles, "", "  ")
		if err != nil {
			return fmt.Errorf("encode AWS satellite role map: %w", err)
		}
		rolesBytes = append(rolesBytes, '\n')
		data.AWSRegion = deployment.AWS.Region
		data.RolesHash = sha256Hex(rolesBytes)
	} else {
		if options.TerraformOutput != "" {
			return errors.New("--terraform-output is only valid for an AWS deployment")
		}
		data.CloudflareEnv = cloudflareEnvironmentNames(deployment, true)
		explicitR2Credentials, parseErr := explicitCloudflareR2CredentialNames(configBytes)
		if parseErr != nil {
			return fmt.Errorf("inspect local Cloudflare credential settings: %w", parseErr)
		}
		data.PreviewCloudflareEnv = cloudflareEnvironmentNames(deployment, !explicitR2Credentials)
	}

	rolesSHA := data.RolesHash
	if rolesSHA == "" {
		rolesSHA = "not-applicable"
	}
	outputs, err := renderOutputs(data, rolesBytes)
	if err != nil {
		return err
	}
	repository := options.Repository
	if repository == "" {
		repository = inferRepository(root)
	}
	if repository != "" && !validateRepository(repository) {
		return errors.New("--repository must be OWNER/REPOSITORY")
	}
	options.Repository = repository
	return writeOutputs(root, outputs, rolesBytes, rolesSHA, options)
}

func resolveRoot(directory string) (string, error) {
	if directory == "" {
		directory = "."
	}
	absolute, err := filepath.Abs(directory)
	if err != nil {
		return "", fmt.Errorf("resolve output directory: %w", err)
	}
	root, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", fmt.Errorf("resolve output directory: %w", err)
	}
	info, err := os.Stat(root)
	if err != nil {
		return "", fmt.Errorf("inspect output directory: %w", err)
	}
	if !info.IsDir() {
		return "", errors.New("output directory must be a directory")
	}
	return filepath.Clean(root), nil
}

func readLocalInput(root, path, description string) ([]byte, error) {
	if strings.Contains(path, "://") {
		return nil, fmt.Errorf("%s must be a local file path; remote config locators are not supported by registry setup", description)
	}
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	absolute, err := filepath.Abs(path)
	if err != nil {
		return nil, fmt.Errorf("resolve %s: %w", description, err)
	}
	relative, err := filepath.Rel(root, absolute)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return nil, fmt.Errorf("%s must be inside the --directory root", description)
	}
	parts := strings.Split(relative, string(filepath.Separator))
	current := root
	for index, part := range parts {
		current = filepath.Join(current, part)
		info, statErr := os.Lstat(current)
		if statErr != nil {
			return nil, fmt.Errorf("read %s: %w", description, statErr)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("%s path must not traverse a symlink", description)
		}
		if index < len(parts)-1 && !info.IsDir() {
			return nil, fmt.Errorf("%s parent path must be a directory", description)
		}
		if index == len(parts)-1 && !info.Mode().IsRegular() {
			return nil, fmt.Errorf("%s must be a regular file, not a symlink or directory", description)
		}
	}
	contents, err := os.ReadFile(absolute)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", description, err)
	}
	return contents, nil
}

func parseRoles(contents []byte, deployment config.DeploymentConfig) (map[string]string, error) {
	decoder := json.NewDecoder(bytes.NewReader(contents))
	token, err := decoder.Token()
	if err != nil {
		return nil, fmt.Errorf("decode Terraform satellite_role_arns JSON: %w", err)
	}
	if token != json.Delim('{') {
		return nil, errors.New("Terraform satellite_role_arns output must be a JSON object keyed by site ID")
	}
	roles := make(map[string]string)
	for decoder.More() {
		keyToken, err := decoder.Token()
		if err != nil {
			return nil, fmt.Errorf("decode Terraform satellite_role_arns site ID: %w", err)
		}
		siteID, ok := keyToken.(string)
		if !ok {
			return nil, errors.New("Terraform satellite_role_arns keys must be site ID strings")
		}
		if _, duplicate := roles[siteID]; duplicate {
			return nil, fmt.Errorf("Terraform satellite_role_arns contains duplicate site %q", siteID)
		}
		var arn string
		if err := decoder.Decode(&arn); err != nil {
			return nil, fmt.Errorf("Terraform satellite_role_arns for site %q must be a string role ARN: %w", siteID, err)
		}
		roles[siteID] = arn
	}
	end, err := decoder.Token()
	if err != nil {
		return nil, fmt.Errorf("decode Terraform satellite_role_arns JSON object end: %w", err)
	}
	if end != json.Delim('}') {
		return nil, errors.New("Terraform satellite_role_arns output must be a JSON object keyed by site ID")
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return nil, errors.New("Terraform satellite_role_arns output must contain exactly one JSON value")
	}
	for siteID, arn := range roles {
		if err := registry.ValidateSiteID(siteID); err != nil {
			return nil, fmt.Errorf("Terraform satellite_role_arns has invalid site ID %q: %w", siteID, err)
		}
		if _, registered := deployment.Sites[siteID]; !registered {
			return nil, fmt.Errorf("Terraform satellite_role_arns contains unregistered site %q", siteID)
		}
		match := roleARNPattern.FindStringSubmatch(arn)
		if match == nil {
			return nil, fmt.Errorf("Terraform satellite_role_arns for site %q must be an AWS IAM role ARN", siteID)
		}
		if deployment.AWS.AccountID != "" && match[2] != deployment.AWS.AccountID {
			return nil, fmt.Errorf("Terraform satellite_role_arns for site %q targets a different AWS account than aws.accountId", siteID)
		}
	}
	for siteID := range deployment.Sites {
		if _, exists := roles[siteID]; !exists {
			return nil, fmt.Errorf("Terraform satellite_role_arns has no role for registered site %q", siteID)
		}
	}
	return roles, nil
}

func cloudflareEnvironmentNames(deployment config.DeploymentConfig, includeAPIToken bool) []string {
	target := deployment.Cloudflare
	values := []string{
		target.AccessKeyIDEnv,
		target.SecretAccessKeyEnv,
		target.SessionTokenEnv,
		target.RegistryReaderAccessKeyIDEnv,
		target.RegistryReaderSecretAccessKeyEnv,
		target.RegistryReaderSessionTokenEnv,
	}
	if includeAPIToken {
		values = append(values, target.APITokenEnv)
	}
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		if value != "" {
			set[value] = struct{}{}
		}
	}
	names := make([]string, 0, len(set))
	for name := range set {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func explicitCloudflareR2CredentialNames(contents []byte) (bool, error) {
	var raw struct {
		Cloudflare *struct {
			AccessKeyIDEnv     *string `yaml:"accessKeyIdEnv"`
			SecretAccessKeyEnv *string `yaml:"secretAccessKeyEnv"`
		} `yaml:"cloudflare"`
	}
	if err := yaml.Unmarshal(contents, &raw); err != nil {
		return false, err
	}
	return raw.Cloudflare != nil && raw.Cloudflare.AccessKeyIDEnv != nil && raw.Cloudflare.SecretAccessKeyEnv != nil, nil
}

func renderOutputs(data templateData, rolesBytes []byte) (map[string][]byte, error) {
	for repository, setter := range map[string]func(actionPin){
		"artifact-pages/publish-action":         func(pin actionPin) { data.PublishSHA, data.PublishVersion = pin.SHA, pin.Version },
		"artifact-pages/preview-action":         func(pin actionPin) { data.PreviewSHA, data.PreviewVersion = pin.SHA, pin.Version },
		"artifact-pages/registry-action":        func(pin actionPin) { data.RegistrySHA, data.RegistryVersion = pin.SHA, pin.Version },
		"aws-actions/configure-aws-credentials": func(pin actionPin) { data.AWSCredsSHA, data.AWSCredsVersion = pin.SHA, pin.Version },
	} {
		pin, ok := pins[repository]
		if !ok || !pinSHAPattern.MatchString(pin.SHA) || !strings.HasPrefix(pin.Version, "v") {
			return nil, fmt.Errorf("no verified offline release pin is bundled for %s", repository)
		}
		setter(pin)
	}
	if data.RolesHash == "" {
		data.RolesHash = "not-applicable"
	}

	files := map[string]string{
		".github/workflows/publish-site.yml":   "publish-site.yml.tmpl",
		".github/workflows/preview-site.yml":   "preview-site.yml.tmpl",
		".github/workflows/registry.yml":       "registry.yml.tmpl",
		".github/actions/site-sync/action.yml": "action.yml.tmpl",
	}
	outputs := make(map[string][]byte, len(files)+1)
	for path, name := range files {
		contents, err := renderTemplate(name, data)
		if err != nil {
			return nil, err
		}
		contents = addManagedDigest(contents)
		outputs[path] = contents
	}
	if data.Provider == "aws" {
		outputs[".github/actions/site-sync/aws-roles.json"] = rolesBytes
	}
	return outputs, nil
}

func renderTemplate(name string, data templateData) ([]byte, error) {
	parsed, err := template.New(name).Delims("<<", ">>").Option("missingkey=error").ParseFS(templateFiles, "templates/"+name)
	if err != nil {
		return nil, fmt.Errorf("parse embedded template %s: %w", name, err)
	}
	var buffer bytes.Buffer
	if err := parsed.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("render embedded template %s: %w", name, err)
	}
	return buffer.Bytes(), nil
}

func writeOutputs(root string, outputs map[string][]byte, rolesBytes []byte, rolesSHA string, options Options) error {
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var missingOrDrift []string
	existing := make(map[string][]byte, len(paths))
	for _, relative := range paths {
		// Preflight every path without creating directories. Generation only
		// creates them later, after all overwrite checks have passed.
		path, info, err := inspectOutput(root, relative, true)
		if err != nil {
			return err
		}
		if info == nil {
			missingOrDrift = append(missingOrDrift, relative)
			continue
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated file %s: %w", relative, err)
		}
		existing[relative] = contents
		if !bytes.Equal(contents, outputs[relative]) {
			missingOrDrift = append(missingOrDrift, relative)
		}
	}
	if options.Check {
		if len(missingOrDrift) != 0 {
			return fmt.Errorf("%w: %s", errDrift, strings.Join(missingOrDrift, ", "))
		}
		fmt.Fprintln(options.Output, "registry setup: generated files are up to date")
		return nil
	}

	for _, relative := range paths {
		current, present := existing[relative]
		if present && bytes.Equal(current, outputs[relative]) {
			continue
		}
		if present && !managedOutput(relative, current, existing, rolesSHA, rolesBytes) {
			return fmt.Errorf("refusing to overwrite unmanaged or manually edited file %s; move it aside, review it, then rerun registry setup", relative)
		}
	}
	for _, relative := range paths {
		current, present := existing[relative]
		if present && bytes.Equal(current, outputs[relative]) {
			continue
		}
		if err := atomicWrite(root, relative, outputs[relative]); err != nil {
			return err
		}
	}
	if len(missingOrDrift) == 0 {
		fmt.Fprintln(options.Output, "registry setup: generated files are up to date")
	} else {
		fmt.Fprintf(options.Output, "registry setup: generated %s\n", strings.Join(missingOrDrift, ", "))
	}
	printManualSteps(options.Output, options.Repository, outputs, rolesBytes)
	return nil
}

func managedOutput(relative string, current []byte, existing map[string][]byte, rolesSHA string, rolesBytes []byte) bool {
	if relative != ".github/actions/site-sync/aws-roles.json" {
		lines := bytes.SplitN(current, []byte("\n"), 3)
		if len(lines) != 3 || !bytes.HasPrefix(lines[0], []byte(generatedHeader+" ")) || !bytes.HasPrefix(lines[1], []byte("# managed-sha256: ")) {
			return false
		}
		return strings.TrimPrefix(string(lines[1]), "# managed-sha256: ") == sha256Hex(lines[2])
	}
	if bytes.Equal(current, rolesBytes) {
		return true
	}
	metadata, ok := existing[".github/actions/site-sync/action.yml"]
	if !ok {
		return false
	}
	markerPrefix := "# aws-roles.json sha256: "
	for _, line := range strings.Split(string(metadata), "\n") {
		if strings.HasPrefix(line, markerPrefix) {
			oldHash := strings.TrimPrefix(line, markerPrefix)
			return oldHash == sha256Hex(current) && rolesSHA != "not-applicable"
		}
	}
	return false
}

func addManagedDigest(contents []byte) []byte {
	firstLine := bytes.IndexByte(contents, '\n')
	if firstLine < 0 {
		return contents
	}
	body := contents[firstLine+1:]
	header := fmt.Sprintf("# managed-sha256: %s\n", sha256Hex(body))
	result := make([]byte, 0, len(contents)+len(header))
	result = append(result, contents[:firstLine+1]...)
	result = append(result, header...)
	result = append(result, body...)
	return result
}

func inspectOutput(root, relative string, check bool) (string, os.FileInfo, error) {
	clean := filepath.Clean(filepath.FromSlash(relative))
	if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", nil, fmt.Errorf("invalid generated output path %q", relative)
	}
	parts := strings.Split(clean, string(filepath.Separator))
	current := root
	for _, part := range parts[:len(parts)-1] {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			if check {
				return filepath.Join(root, clean), nil, nil
			}
			if err := os.Mkdir(current, 0o755); err != nil && !errors.Is(err, os.ErrExist) {
				return "", nil, fmt.Errorf("create generated directory %s: %w", filepath.ToSlash(filepath.Join(parts[:len(parts)-1]...)), err)
			}
			info, err = os.Lstat(current)
		}
		if err != nil {
			return "", nil, fmt.Errorf("inspect generated directory %s: %w", relative, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", nil, fmt.Errorf("generated output path %s traverses a symlink directory", relative)
		}
		if !info.IsDir() {
			return "", nil, fmt.Errorf("generated output path parent %s is not a directory", relative)
		}
	}
	path := filepath.Join(root, clean)
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return path, nil, nil
	}
	if err != nil {
		return "", nil, fmt.Errorf("inspect generated file %s: %w", relative, err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return "", nil, fmt.Errorf("generated output %s must be a regular file, not a symlink or directory", relative)
	}
	return path, info, nil
}

func atomicWrite(root, relative string, contents []byte) error {
	path, info, err := inspectOutput(root, relative, false)
	if err != nil {
		return err
	}
	if info != nil && !info.Mode().IsRegular() {
		return fmt.Errorf("generated output %s must be a regular file", relative)
	}
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".artifact-pages-registry-setup-*")
	if err != nil {
		return fmt.Errorf("create temporary generated file for %s: %w", relative, err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("set permissions for generated file %s: %w", relative, err)
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write generated file %s: %w", relative, err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("sync generated file %s: %w", relative, err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close generated file %s: %w", relative, err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace generated file %s: %w", relative, err)
	}
	return nil
}

func printManualSteps(output io.Writer, repository string, outputs map[string][]byte, rolesBytes []byte) {
	if output == nil {
		return
	}
	if repository == "" {
		repository = "OWNER/ADMIN_REPOSITORY"
	}
	fmt.Fprintln(output, "Manual GitHub setup (these commands are printed only; registry setup does not call GitHub):")
	fmt.Fprintln(output, "  # For a private admin repository, allow repositories in the organization to call its workflows.")
	fmt.Fprintf(output, "  gh api --method PUT repos/%s/actions/permissions/access --field access_level=organization\n", repository)
	if strings.Contains(string(outputs[".github/workflows/registry.yml"]), "${{ secrets.") {
		var names []string
		for _, line := range strings.Split(string(outputs[".github/workflows/registry.yml"]), "\n") {
			if strings.Contains(line, "${{ secrets.") {
				start := strings.Index(line, "${{ secrets.") + len("${{ secrets.")
				end := strings.Index(line[start:], " }")
				if end >= 0 {
					names = append(names, line[start:start+end])
				}
			}
		}
		names = uniqueSorted(names)
		fmt.Fprintln(output, "  # Set caller secrets (or equivalent organization secrets) for each site repository.")
		for _, name := range names {
			fmt.Fprintf(output, "  gh secret set %s --repo OWNER/SITE_REPOSITORY\n", name)
		}
		fmt.Fprintln(output, "  # Registry pull-request dry-runs do not select an environment, so set admin secrets at repository scope.")
		for _, name := range names {
			fmt.Fprintf(output, "  gh secret set %s --repo %s\n", name, repository)
		}
		fmt.Fprintln(output, "  # Optional: production environment secrets of the same names override repository values on production runs.")
		for _, name := range names {
			fmt.Fprintf(output, "  gh secret set %s --repo %s --env production\n", name, repository)
		}
	}
	if len(rolesBytes) != 0 {
		fmt.Fprintln(output, "  # Terraform role output is public metadata; commit the generated map with the admin files.")
		fmt.Fprintln(output, "  terraform output -json satellite_role_arns > satellite-role-arns.json")
		fmt.Fprintln(output, "  artifact-pages registry setup --terraform-output satellite-role-arns.json")
		fmt.Fprintf(output, "  gh variable set ARTIFACT_PAGES_REGISTRY_ADMIN_ROLE_ARN --repo %s --body \"$(terraform output -raw admin_role_arn)\"\n", repository)
	}
}

func uniqueSorted(values []string) []string {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		set[value] = struct{}{}
	}
	out := make([]string, 0, len(set))
	for value := range set {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func sha256Hex(contents []byte) string {
	sum := sha256.Sum256(contents)
	return hex.EncodeToString(sum[:])
}

func validateRepository(repository string) bool {
	parts := strings.Split(repository, "/")
	return len(parts) == 2 && repositoryPart.MatchString(parts[0]) && repositoryPart.MatchString(parts[1])
}

func inferRepository(root string) string {
	command := exec.Command("git", "-C", root, "config", "--get", "remote.origin.url")
	output, err := command.Output()
	if err != nil {
		return ""
	}
	remote := strings.TrimSpace(string(output))
	if strings.HasPrefix(remote, "git@github.com:") {
		remote = strings.TrimPrefix(remote, "git@github.com:")
	} else if parsed, parseErr := url.Parse(remote); parseErr == nil && parsed.Host == "github.com" {
		remote = strings.TrimPrefix(parsed.Path, "/")
	} else {
		return ""
	}
	remote = strings.TrimSuffix(remote, ".git")
	if validateRepository(remote) {
		return remote
	}
	return ""
}

// IsDrift reports whether Run failed only because --check found stale output.
func IsDrift(err error) bool { return errors.Is(err, errDrift) }
